//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrontUsuario.ServiceUsuariosR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BUsuarios", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class BUsuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuariosR.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/InsertarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/InsertarUsuarioResponse")]
        bool InsertarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/InsertarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EditarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EditarUsuarioResponse")]
        string EditarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EditarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<string> EditarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        string EliminarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<string> EliminarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : WebFrontUsuario.ServiceUsuariosR.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<WebFrontUsuario.ServiceUsuariosR.IServiceUsuario>, WebFrontUsuario.ServiceUsuariosR.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.InsertarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.InsertarUsuarioAsync(usuario);
        }
        
        public string EditarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.EditarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<string> EditarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.EditarUsuarioAsync(usuario);
        }
        
        public string EliminarUsuario(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.EliminarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<string> EliminarUsuarioAsync(WebFrontUsuario.ServiceUsuariosR.BUsuarios usuario) {
            return base.Channel.EliminarUsuarioAsync(usuario);
        }
    }
}
